spring.application.name=signing-request-service

spring.datasource.url=jdbc:postgresql://127.0.0.1:55433/signing_db
spring.datasource.username=signing_user
spring.datasource.password=signing_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration